local M = {
    winblend = 0,
    border_style = "single",
    border_chars = { "─", "│", "─", "│", "┌", "┐", "┘", "└" },
    icons = {
        lsp = {
            Class = "",
            Color = "󰏘",
            Constant = "󰏿",
            Constructor = "",
            Enum = "",
            EnumMember = "",
            Event = "",
            Field = "󰜢",
            File = "",
            Folder = "",
            Function = "󰊕",
            Interface = "",
            Keyword = "󰌋",
            Method = "󰆧",
            Module = "",
            Operator = "󰆕",
            Property = "",
            Reference = "",
            Snippet = "",
            Struct = "󰙅",
            Text = "󰉿",
            TypeParameter = "",
            Unit = "",
            Value = "󰎠",
            Variable = "󰀫",
        },

        diagnostics = {
            error = "",
            warn = "",
            hint = "",
            info = "",
        },

        git = {
            added = "",
            conflict = "",
            deleted = "",
            ignored = "◌",
            modified = "",
            removed = "",
            renamed = "➜",
            staged = "",
            unstaged = "✗",
            untracked = "★",
        },

        git_signs = {
            add = '│',
            change = '│',
            delete = '_',
            topdelete = '‾',
            changedelete = '~',
            untracked = '┆',
        },
    },
}

return M
