#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop=^

# change from the 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr

picom -b --experimental-backends
nitrogen --restore &
