#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 
bspc monitor DP-0 -d 4 5 6 

bspc config border_width        2
bspc config window_gap          7
bspc config split_ratio         0.50
# bspc config borderless_monocle      true
# bspc config gapless_monocle         true

bspc rule -a discord desktop=^2 
bspc rule -a kitty desktop=^5
bspc rule -a Spotify desktop=^3
bspc rule -a firefox desktop=^1

# change from the 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr

picom -b --experimental-backends --config $HOME/.config/picom/picom.conf &
nitrogen --set-zoom-fill --random --head=0 $HOME/wallpapers/ 
nitrogen --set-zoom-fill --random --head=1 $HOME/wallpapers/ 
