#!/usr/bin/env bash

fzf --preview "kitty icat --clear --transfer-mode=memory --stdin=no --place="${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0" {} " --preview-window down:25 --layout=reverse --multi
